<?php
// FILE: fsbhoa-uhppote-cli.php
//
// Every uhppote-cli command the plugin runs goes through these helpers, so each one
// passes --config with a file generated from ac_controllers. The default
// /etc/uhppoted/uhppoted.conf is hand-written for manual testing and lists every
// controller (testbed and production), so program code must never rely on it.

if ( ! defined( 'WPINC' ) ) { die; }

define( 'FSBHOA_UHPPOTE_CLI_CONFIG', '/var/lib/fsbhoa/uhppoted.conf' );

/**
 * Writes the uhppote-cli config from the UHPPOTE controllers in ac_controllers.
 * Called whenever controllers.json is regenerated and when the Event Service settings are saved.
 * Controllers without an IP address are left out, so commands to them are refused
 * instead of being broadcast.
 *
 * @return bool True if the file was written.
 */
function fsbhoa_uhppote_write_cli_config() {
    global $wpdb;

    $controllers = $wpdb->get_results(
        "SELECT uhppoted_device_id, friendly_name, ip_address FROM ac_controllers WHERE type = 'UHPPOTE' ORDER BY uhppoted_device_id"
    );
    if ( $wpdb->last_error ) {
        error_log( 'UHPPOTE CLI: Could not read controllers for ' . FSBHOA_UHPPOTE_CLI_CONFIG . ': ' . $wpdb->last_error );
        return false;
    }

    $lines   = [];
    $lines[] = '# Generated by fsbhoa_ac_uhppote from ac_controllers. Do not edit; changes are overwritten.';
    $lines[] = 'bind.address = ' . sanitize_text_field( get_option( 'fsbhoa_ac_bind_addr', '0.0.0.0:0' ) );
    $lines[] = 'broadcast.address = ' . sanitize_text_field( get_option( 'fsbhoa_ac_broadcast_addr', '192.168.42.255:60000' ) );

    foreach ( $controllers as $c ) {
        $device_id = absint( $c->uhppoted_device_id );
        $ip        = trim( (string) $c->ip_address );
        if ( ! $device_id || $ip === '' ) {
            error_log( "UHPPOTE CLI: Controller {$device_id} has no IP address; left out of the CLI config." );
            continue;
        }
        if ( strpos( $ip, ':' ) === false ) {
            $ip .= ':60000';
        }
        $lines[] = '';
        $lines[] = '# ' . preg_replace( '/[\r\n]+/', ' ', (string) $c->friendly_name );
        $lines[] = "{$device_id}.address = {$ip}";
        $lines[] = "UT0311-L0x.{$device_id}.address = {$ip}";
    }

    $dir = dirname( FSBHOA_UHPPOTE_CLI_CONFIG );
    if ( ! is_dir( $dir ) ) {
        mkdir( $dir, 0755, true );
    }
    if ( file_put_contents( FSBHOA_UHPPOTE_CLI_CONFIG, implode( "\n", $lines ) . "\n" ) === false ) {
        error_log( 'UHPPOTE CLI: Could not write ' . FSBHOA_UHPPOTE_CLI_CONFIG );
        return false;
    }
    return true;
}

/**
 * Returns the device IDs that have an address in the generated config (read once per request).
 * Creates the config first if it doesn't exist yet.
 *
 * @return array [device_id => true]
 */
function fsbhoa_uhppote_cli_configured_devices() {
    static $devices = null;
    if ( $devices !== null ) {
        return $devices;
    }

    if ( ! file_exists( FSBHOA_UHPPOTE_CLI_CONFIG ) ) {
        fsbhoa_uhppote_write_cli_config();
    }

    $devices  = [];
    $contents = @file_get_contents( FSBHOA_UHPPOTE_CLI_CONFIG );
    if ( $contents !== false && preg_match_all( '/^(\d+)\.address\s*=/m', $contents, $m ) ) {
        foreach ( $m[1] as $id ) {
            $devices[ (string) $id ] = true;
        }
    }
    return $devices;
}

/**
 * Builds a uhppote-cli command line that uses the generated config.
 * Use this for logging and dry-run output; run commands with fsbhoa_uhppote_cli_exec().
 *
 * @param string $args    Command and arguments, already escaped (e.g. "set-time 425043852").
 * @param string $options Extra global options placed before the command (e.g. "--timeout 2s").
 * @return string
 */
function fsbhoa_uhppote_cli_command( $args, $options = '' ) {
    $cmd = 'uhppote-cli --config ' . escapeshellarg( FSBHOA_UHPPOTE_CLI_CONFIG );
    if ( $options !== '' ) {
        $cmd .= ' ' . $options;
    }
    return $cmd . ' ' . $args;
}

/**
 * Runs a uhppote-cli command for one controller, with the generated config.
 * Fails closed: if the controller has no address in the config, the command is not run,
 * because uhppote-cli would otherwise broadcast it to every controller on the network.
 *
 * @param int|string $device_id Controller serial number the command is for.
 * @param string     $args      Command and arguments, already escaped.
 * @param string     $options   Extra global options (e.g. "--timeout 2s").
 * @return string Command output (stdout and stderr), or a line starting with "ERROR:" if refused.
 */
function fsbhoa_uhppote_cli_exec( $device_id, $args, $options = '' ) {
    $devices = fsbhoa_uhppote_cli_configured_devices();
    if ( ! isset( $devices[ (string) absint( $device_id ) ] ) ) {
        $msg = "ERROR: Controller {$device_id} has no address in " . FSBHOA_UHPPOTE_CLI_CONFIG . '; command not sent (it would be broadcast).';
        error_log( 'UHPPOTE CLI: ' . $msg . ' Command: ' . $args );
        return $msg;
    }
    return (string) shell_exec( fsbhoa_uhppote_cli_command( $args, $options ) . ' 2>&1' );
}
